CREATE DATABASE Atm;

USE Atm;

CREATE TABLE Atm(
	Name VARCHAR(60) NOT NULL,
	AvailableCash DECIMAL NOT NULL,
);

CREATE TABLE Users (
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	FullName VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Password NVARCHAR(MAX) NOT NULL,
	PhoneNumber VARCHAR(20) NOT NULL,
	UserBank VARCHAR(50) NOT NULL,
    Role VARCHAR(50) NOT NULL
	);


	CREATE TABLE Admin (
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	AdminId INT NOT NULL,
	FOREIGN KEY (AdminId) REFERENCES Users(Id)
	);
	
	CREATE TABLE Customer (
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CustomerId INT NOT NULL,
	FOREIGN KEY (CustomerId) REFERENCES Users(Id)
	);

	CREATE TABLE ThirdParty (
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ThirdPartyId INT NOT NULL,
	FOREIGN KEY (ThirdPartyId) REFERENCES Users(Id)
	);

CREATE TABLE Account(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	UserId INT NOT NULL,
	UserName VARCHAR(100) NOT NULL,
	AccounType VARCHAR(50) NOT NULL,
	Pin	VARCHAR(MAX) NOT NULL,
	Balance DECIMAL NOT NULL,
	CreateDate DATETIME NOT NULL,
	FOREIGN KEY (UserId) REFERENCES Users (Id)
);

--End of users information query

CREATE TABLE Bank(
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	UserId INT NOT NULL,
	Name VARCHAR(50) NOT NULL,
	SwiftCode NVARCHAR(500) NOT NULL,
	FOREIGN KEY (UserId) REFERENCES Users(UserId)
);

CREATE TABLE Bill(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Amount DECIMAL NOT NULL,
);	
